openapi: "3.0.1"

info:
  title: Delivery Fee Calculator API
  description: OpenAPI specifications for Delivery Fee Calculator endpoints
  version: "0.1"

servers:
  - url: /

paths:
  /delivery_calculator:
    post:
      summary: Compute and retrieve delivery fee
      operationId: monolith.views.delivery.delivery_calculator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryOrder'
      responses:
        200:
          description: Return delivery fee (cents) and status
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseSuccess'
        422:
          description: Invalid paramaters, return message error and status
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseError'
        default:
          description: An error occurred while processing the delivery fee

components:
  schemas:
    DeliveryOrder:
      type: object
      required:
        - cart_value
        - delivery_distance
        - number_of_items
        - time
      properties:
        cart_value:
          description: Value of the shopping cart in cents (integer)
          example: 790
        delivery_distance:
          description: The distance between the store and customer's location in meters (integer)
          example: 2235
        number_of_items:
          description: The number of items in the customer's shopping cart (integer)
          example: 4
        time:
          description: Order time in ISO format (string)
          example: '2023-09-25T13:00:00Z'
    ResponseSuccess:
      type: object
      required:
        - status
        - delivery_fee
      properties:
        status:
          type: string
          description: Status of the request
          example: Success
        delivery_fee:
          type: integer
          description: Total delivery fee (in cents)
          example: 710
    ResponseError:
        type: object
        required:
          - status
          - message
        properties:
          status:
            type: string
            example: Failed
          message:
            type: object
            description: List of invalid arguments and corresponding problem
            example: '{cart_value: ["Must be greater than or equal to 1.]}"'